### ISSUE TITLE
dumping the firmware

### ISSUE THREAD

**Issue by Rukongai** [g992/flashforge-ad5m-5mpro-research#2]
i'm not familiar with the T113-s3, but i'm seeing a SWD and ISP header on the board. Have you tried dumping the firmware?

**Comment by g992** [comment]
hello! The T113-S3 is a Linux controller. I have a guide for getting Root's rights, you can get them yourself and access his memory. If you need the firmware of the microcontroller, then it usually lies in the update folder.the bin file. It's him.

**Comment by xplayerxpasha** [comment]
May be you have dump Emmc with extcsd and full dump.

**Comment by g992** [comment]
I'm sorry, I don't have a dump, as there is no equipment to remove it.

**Comment by xplayerxpasha** [comment]
u dont have dumper or remove emmc ?

**Comment by xplayerxpasha** [comment]
I have emmc connection points on the board
