### ISSUE TITLE
Parts for Housing

### ISSUE THREAD

**Issue by Make-o-Rama** [g992/flashforge-ad5m-5mpro-research#3]
Hoi,

i just got my FF AD5M and i´m testing it right now. I like the printer very much. I thought to design some components for the housing. I mean i´m okish in 3D designing and it would be a very great topic for my channel.

Would you mind if i commit it in your repo?

Regards
Maggy

**Comment by g992** [comment]
Certainly! I will only be glad if you add the files to the repository. A little later I will rewrite the readme file to make navigation easier. in the meantime, you can commit them in the upgrades/housing folder without any problems
