### ISSUE TITLE
SIlent psu fan

### ISSUE THREAD

**Issue by ps1x** [g992/flashforge-ad5m-5mpro-research#7]
I went other route, i made Y-splitter with fan JST (not sure about connector name here) connector which is inserted into motherboard light output, then one tail goes to light, one back to PSU fan, so fan only works when light is on. This is much cheaper and eco-friendly then buying new PSU.

**Comment by ps1x** [comment]
Forgot to tell, i also added voltage regulator board before fan to reduce its speed..

**Comment by g992** [comment]
Nice mod! I installed mw psu not only because it has auto shutdown, but also because I don't trust Chinese power supplies :) I'm used to working with mean well, I fully support other power supplies, and I will be glad if you write a .md file about yours upgrade

**Comment by anti-vaxxer** [comment]
Hi @ps1x @g992 !,
instead of buying new PSU would it be a good idea to open the PSU and add a thermal switch to the fan wire? so the fan turns on only when thermal switch reaches certain temperature.
Thermal Switch example https://www.aliexpress.com/item/1005006103476719.html

**Comment by g992** [comment]
I am wary of opening and interfering with the operation of power supplies (perhaps I am being too careful) and it was easier for me to change the power supply
But your solution is also quite good, I think it's the best option of the cheap ones
